language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.10.6
env:
  global:
    secure: cnAbwM3DWJip9P4eedqg6+8xTs4HSHDBt5Zm3vFjV6nA4ttDEVbdAW5osnqa4d743xwgi8W8sRm/2QoBKNADtvaxnMCesqPB6XjuQ6acM5i7a3nMBXR56LyYDPJCnnMQqryArvuO5PO0NKboVV9Cv6JvwfQY+9Bex7W7hr1jsIEdNxxKj2bIMFFxmVrGozgiwZMxwNykCPpZ8aXI1h4LUjulW0yzj3yRey70u81UD7fcZNtxM2DxduchjrIuJ4KZDfCAtudyPuavqsry+5zlyqV9KtyIAR7+CraOmS0YItnhDvRTbC1H+1PProi7sYGJOOzvCpdNYykSTQFRE1RPlKSUChEqGD3Rv1UwZ5lpeWtAojW+kdwfQG/X5X5xwVzC6BSPl+4afoVmbpTOJoaA5cKvBGGZ7VIk4s91JjvBxsdDg8rcnhZaxTMKdhoxk7c5QXv5qr87d/pXngDVeIYUbgCqEwcNgfBBpNXtG4VHIVgTi/fmEjCqg1eeQhJdyfgH61UNQ1JHZsUNDMMHWR4Pem4NQxkqSZJR+xkFNc8LYR/HjRWWCARUBOESNQqMTmA35mKl24Mwj0wqn9F3zAEMUZjHKDSu0I/R1MORF+99C3T3qdIko/vr34H6cQVboL07jVftaWYNDN+Ah/Q/L4CnCyfa2fdIv/oqCX9al/lHOOk=
